user_name_min_long: 5
user_email_min_long: 5
user_password_min_long: 5
words_paginate: 5
categories_paginate: 5
lesson_max_word: 2

word:
  user_learned: "id IN (SELECT word_id FROM lesson_words WHERE lesson_id IN (SELECT id FROM lessons WHERE user_id = %{idx}))"
  user_unlearned: "id NOT IN (SELECT word_id FROM lesson_words WHERE lesson_id IN (SELECT id FROM lessons WHERE user_id = %{idx}))"
  user_passed: "id IN (SELECT word_id FROM lesson_words WHERE ((lesson_id IN (SELECT id FROM lessons WHERE user_id = %{idx})) AND (answer_id IN (SELECT id FROM answers WHERE correct = 't'))))"
  lesson_passed: "id IN (SELECT word_id FROM lesson_words WHERE ((lesson_id = %{lesson_id}) AND (answer_id IN (SELECT id FROM answers WHERE correct = 't'))))"
  filter_content: "content LIKE '%{chr37}%{content}%{chr37}'"
